let speed = 30
let strip = neopixel.create(DigitalPin.P8, 4, NeoPixelMode.RGB)
strip.clear()
basic.forever(function () {
    mecanumRobot.setLed(LedCount.Left, LedState.ON)
    mecanumRobot.setLed(LedCount.Right, LedState.ON)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    mecanumRobot.Motor(LR.Upper_left, MD.Forward, speed)
    mecanumRobot.Motor(LR.Lower_left, MD.Forward, speed)
    mecanumRobot.Motor(LR.Upper_right, MD.Forward, speed)
    mecanumRobot.Motor(LR.Lower_right, MD.Forward, speed)
    mecanumRobot.setLed(LedCount.Left, LedState.OFF)
    mecanumRobot.setLed(LedCount.Right, LedState.OFF)
    strip.clear()
    basic.pause(2000)
    mecanumRobot.setLed(LedCount.Left, LedState.ON)
    mecanumRobot.setLed(LedCount.Right, LedState.ON)
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    mecanumRobot.Motor(LR.Upper_left, MD.Back, speed)
    mecanumRobot.Motor(LR.Lower_left, MD.Back, speed)
    mecanumRobot.Motor(LR.Upper_right, MD.Back, speed)
    mecanumRobot.Motor(LR.Lower_right, MD.Back, speed)
    mecanumRobot.setLed(LedCount.Left, LedState.OFF)
    mecanumRobot.setLed(LedCount.Right, LedState.OFF)
    strip.clear()
    basic.pause(2000)
    mecanumRobot.setLed(LedCount.Left, LedState.ON)
    mecanumRobot.setLed(LedCount.Right, LedState.ON)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    mecanumRobot.Motor(LR.Upper_left, MD.Back, speed)
    mecanumRobot.Motor(LR.Lower_left, MD.Back, speed)
    mecanumRobot.Motor(LR.Upper_right, MD.Forward, speed)
    mecanumRobot.Motor(LR.Lower_right, MD.Forward, speed)
    mecanumRobot.setLed(LedCount.Left, LedState.OFF)
    mecanumRobot.setLed(LedCount.Right, LedState.OFF)
    strip.clear()
    basic.pause(2000)
    mecanumRobot.setLed(LedCount.Left, LedState.ON)
    mecanumRobot.setLed(LedCount.Right, LedState.ON)
    strip.showColor(neopixel.colors(NeoPixelColors.Violet))
    mecanumRobot.Motor(LR.Upper_left, MD.Forward, speed)
    mecanumRobot.Motor(LR.Lower_left, MD.Forward, speed)
    mecanumRobot.Motor(LR.Upper_right, MD.Back, speed)
    mecanumRobot.Motor(LR.Lower_right, MD.Back, speed)
    mecanumRobot.setLed(LedCount.Left, LedState.OFF)
    mecanumRobot.setLed(LedCount.Right, LedState.OFF)
    strip.clear()
    basic.pause(2000)
    mecanumRobot.state(MotorState.stop)
    basic.pause(2000)
})
